from selene import browser, have, be, by, command
import time

from selene.support.conditions.be import clickable


def test_chose_language():
    browser.open("/")
    browser.element('[class="content"]').click()
    browser.element("//div[contains(@class, 'context-menu__option') and .//span[text()='English (США)']]").click()
    browser.element('[class="content"]').should(have.text('English'))


def test_input_unvalid_mail():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('почта@.ru').press_tab()
    browser.element(".form-field__error.no-select").should(have.text('Неверный адрес электронной почты'))

def test_input_valid_mail():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('.hdi_title').should(have.text('Проверьте почту'))

def test_wrong_code():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('664555')
    browser.element('.cd_code__error').should(have.text('Код введен неправильно'))

def test_success_code():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('.hdi_title.hdi_title_nodescription').wait_until(have.text('Похоже, вы еще не используете Lenza'))

def test_create_workspace_correct_name():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element('#domain-company').type('test_name_24')
    time.sleep(1)
    browser.element("//span[@class='btn__title']").click()
    browser.element(".pr_profile").should(have.text('Настройка личного профиля'))

def test_create_workspace_incorrect_name():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd9@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element('#domain-company').type('te')
    browser.element(".form-field__error").should(have.text('Имя домена не может быть короче 3-х символов'))

def test_create_workspace_incorrect_name_with_symbol():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd9@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element('#domain-company').type('***')
    browser.element(".form-field__error").should(have.text('Разрешены латинские буквы и символы aA-zZ, 0-9, -, _'))

def test_movie_back_workspace():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(".d_domain__back-link").click()
    browser.element('.hdi_title.hdi_title_nodescription').wait_until(have.text('Похоже, вы еще не используете Lenza'))


def test_fill_only_name():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(by.text("Мне понятно. Вперед!")).click()
    browser.element("//input[@placeholder='Введите имя']").type('Имя')
    browser.element("#rcaec']").should(be.disabled)

def test_fill_only_surname():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(by.text("Мне понятно. Вперед!")).click()
    browser.element("//input[@placeholder='Введите фамилию']").type('Фамилия')
    browser.element("#rcaec']").should(be.disabled)

def test_load_only_photo_png():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(by.text("Мне понятно. Вперед!")).click()
    browser.element(".avatar__img-upload-input").send_keys('E:\\proect\\lenzaos\\ava.png')
    time.sleep(1)
    browser.element("#rcaec']").should(be.disabled)

def test_load_wrong_photo_format_gif():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(by.text("Мне понятно. Вперед!")).click()
    browser.element(".avatar__img-upload-input").send_keys('E:\\proect\\lenzaos\\ava.gif')
    time.sleep(1)
    browser.element(".pr_profile__avatar_btn").should(have.text('Добавить фотографию'))

def test_load_wrong_photo_format_bmp():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(by.text("Мне понятно. Вперед!")).click()
    browser.element(".avatar__img-upload-input").send_keys('E:\\proect\\lenzaos\\ava.bmp')
    time.sleep(1)
    browser.element(".pr_profile__avatar_btn").should(have.text('Добавить фотографию'))

def test_fill_profile():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(by.text("Мне понятно. Вперед!")).click()
    browser.element("//input[@placeholder='Введите имя']").type('Имя')
    browser.element("//input[@placeholder='Введите фамилию']").type('Фамилия')
    browser.element("#rcaec']").wait_until(be.enabled)

def test_fill_data_birthday():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element(by.text("Мне понятно. Вперед!")).click()
    browser.element("//input[@placeholder='Введите имя']").type('Имя')
    browser.element("//input[@placeholder='Введите фамилию']").type('Фамилия')
    browser.element("//span[@class='btn__title']").should(be.visible).click()
    browser.element("//input[@value='1']").click()
    browser.element(by.text("2")).click()
    browser.element("//input[@value='Январь']").click()
    browser.element(by.text("Март")).click()
    browser.element("//input[@value='1999']").click()
    browser.element(by.text('1995')).perform(command.js.scroll_into_view)
    browser.element(by.text('1995')).click()
    browser.element("//div[contains(@class, 'small-day') and .//span[text()='День']]//input").should(have.value("2"))
    browser.element("//div[contains(@class, 'middle-day')]//input").should(have.value("Март"))
    browser.element("//div[contains(@class, 'small-day')][.//span[text()='Год']]//input").should(have.value("1995"))

def test_invate_friend_wrong_email():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd33@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element('#domain-company').type('test_name_33')
    time.sleep(1)
    browser.element("//span[@class='btn__title']").click()
    browser.element("//input[@placeholder='Введите имя']").type('Имя')
    browser.element("//input[@placeholder='Введите фамилию']").type('Фамилия')
    browser.element("#0psox").wait_until(be.not_.disabled)
    browser.element(by.text("Продолжить")).click()
    browser.element("//input[@value='1']").click()
    browser.element(by.text("2")).click()
    browser.element("//input[@value='Январь']").click()
    browser.element(by.text("Март")).click()
    browser.element("//input[@value='1999']").click()
    browser.element(by.text('1995')).perform(command.js.scroll_into_view).click()
    browser.element("//button[.//span[text()='Продолжить']]").should(be.clickable).click()
    browser.element("//input[@id='tags-row-input']").type("почта").press_enter()
    browser.element(".tag__remove-icon").click()
    browser.element("//input[@id='tags-row-input']").should(have.text(""))

def test_invate_friend_link():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd35@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element('#domain-company').type('test_name_34')
    time.sleep(1)
    browser.element("//span[@class='btn__title']").click()
    browser.element("//input[@placeholder='Введите имя']").type('Имя')
    browser.element("//input[@placeholder='Введите фамилию']").type('Фамилия')
    browser.element("#0psox").wait_until(be.not_.disabled)
    browser.element(by.text("Продолжить")).click()
    browser.element("//input[@value='1']").click()
    browser.element(by.text("2")).click()
    browser.element("//input[@value='Январь']").click()
    browser.element(by.text("Март")).click()
    browser.element("//input[@value='1999']").click()
    browser.element(by.text('1995')).perform(command.js.scroll_into_view).click()
    browser.element("//button[.//span[text()='Продолжить']]").should(be.clickable).click()
    browser.element('.cp_copy').click()
    browser.element(".cp_popup").should(have.text("Ссылка скопирована. Теперь вы можете поделиться ей и с другими!"))

def test_invate_friend_later():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd37@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element('#domain-company').type('test_name_36')
    time.sleep(1)
    browser.element("//span[@class='btn__title']").click()
    browser.element("//input[@placeholder='Введите имя']").type('Имя')
    browser.element("//input[@placeholder='Введите фамилию']").type('Фамилия')
    browser.element("#0psox").wait_until(be.not_.disabled)
    browser.element(by.text("Продолжить")).click()
    browser.element("//input[@value='1']").click()
    browser.element(by.text("2")).click()
    browser.element("//input[@value='Январь']").click()
    browser.element(by.text("Март")).click()
    browser.element("//input[@value='1999']").click()
    browser.element(by.text('1995')).perform(command.js.scroll_into_view).click()
    browser.element("//button[.//span[text()='Продолжить']]").should(be.clickable).click()
    browser.element(".inu_invite__link_skip").click()
    browser.element(".component-dialog-title-title-text").should(have.text('Видео для владельцев и админов'))

def test_invate_friend_valid_mail():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dd47@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    browser.element('#domain-company').type('test_name_47')
    time.sleep(1)
    browser.element("//span[@class='btn__title']").click()
    browser.element("//input[@placeholder='Введите имя']").type('Имя')
    browser.element("//input[@placeholder='Введите фамилию']").type('Фамилия')
    browser.element("#0psox").wait_until(be.not_.disabled)
    browser.element(by.text("Продолжить")).click()
    browser.element("//input[@value='1']").click()
    browser.element(by.text("2")).click()
    browser.element("//input[@value='Январь']").click()
    browser.element(by.text("Март")).click()
    browser.element("//input[@value='1999']").click()
    browser.element(by.text('1995')).perform(command.js.scroll_into_view).click()
    browser.element("//button[.//span[text()='Продолжить']]").should(be.clickable).click()
    browser.element("//input[@id='tags-row-input']").type("example@mail.com").press_enter()
    browser.element("//button[contains(@class, 'inu_invite__buttons_send')]").click()
    browser.element("//p[contains(@class, 'text-size-dialog-title')]").should(have.exact_text("Приглашение отправлено"))

def test_check_profile():
    browser.open('/')
    browser.element('[class="button-ui btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('#email-input').type('dde1@test.com').click()
    browser.element('[class="btn btn--full-width with-border btn--lg no-select"]').click()
    browser.element('[class="code-input__field focus-shadow code-input__field--current"]').type('666555')
    browser.element('[class="list-item__info-wrapper"]').click()
    time.sleep(4)
    #browser.element("#close-view").click()
    browser.element("//button[contains(@class, 'profile-button__menu-item-trigger')]").click()
    browser.element(by.text('OK')).click()
    browser.element('.list-item__info-text').click()
    browser.element(".component-dialog-title-title-text").should(have.text('Имя Фамилия'))





